export const capitalData = [
  {
    id: "1",
    name: "北海道",
    nameKana: "ほっかいどう",
    city: "札幌市",
    cityKana: "さっぽろし",
    fakes: ["函館市", "小樽市", "旭川市"],
    img: "img/imgSingle/hokkaidoSingle.png",
  },
  {
    id: "2",
    name: "青森県",
    nameKana: "あおもりけん",
    city: "青森市",
    cityKana: "あおもりし",
    fakes: ["弘前市", "八戸市", "五所川原市"],
    img: "img/imgSingle/aomoriSingle.png",
  },
  {
    id: "3",
    name: "岩手県",
    nameKana: "いわてけん",
    city: "盛岡市",
    cityKana: "もりおかし",
    fakes: ["宮古市", "釜石市", "岩手市"],
    img: "img/imgSingle/iwateSingle.png",
  },
  {
    id: "4",
    name: "宮城県",
    nameKana: "みやぎけん",
    city: "仙台市",
    cityKana: "せんだいし",
    fakes: ["宮城市", "石巻市", "気仙沼市"],
    img: "img/imgSingle/miyagiSingle.png",
  },
  {
    id: "5",
    name: "秋田県",
    nameKana: "あきたけん",
    city: "秋田市",
    cityKana: "あきたし",
    fakes: ["大館市", "能代市", "横手市"],
    img: "img/imgSingle/akitaSingle.png",
  },
  {
    id: "6",
    name: "山形県",
    nameKana: "やまがたけん",
    city: "山形市",
    cityKana: "やまがたし",
    fakes: ["酒田市", "新庄市", "米沢市"],
    img: "img/imgSingle/yamagataSingle.png",
  },
  {
    id: "7",
    name: "福島県",
    nameKana: "ふくしまけん",
    city: "福島市",
    cityKana: "ふくしまし",
    fakes: ["郡山市", "いわき市", "相馬市"],
    img: "img/imgSingle/fukushimaSingle.png",
  },
  {
    id: "8",
    name: "茨城県",
    nameKana: "いばらきけん",
    city: "水戸市",
    cityKana: "みとし",
    fakes: ["つくば市", "茨城市", "日立市"],
    img: "img/imgSingle/ibarakiSingle.png",
  },
  {
    id: "9",
    name: "栃木県",
    nameKana: "とちぎけん",
    city: "宇都宮市",
    cityKana: "うつのみやし",
    fakes: ["小山市", "栃木市", "佐野市"],
    img: "img/imgSingle/tochigiSingle.png",
  },
  {
    id: "10",
    name: "群馬県",
    nameKana: "ぐんまけん",
    city: "前橋市",
    cityKana: "まえばしし",
    fakes: ["高崎市", "桐生市", "群馬市"],
    img: "img/imgSingle/gunmaSingle.png",
  },
  {
    id: "11",
    name: "埼玉県",
    nameKana: "さいたまけん",
    city: "さいたま市",
    cityKana: "さいたまし",
    fakes: ["川越市", "熊谷市", "川口市"],
    img: "img/imgSingle/saitamaSingle.png",
  },
  {
    id: "12",
    name: "千葉県",
    nameKana: "ちばけん",
    city: "千葉市",
    cityKana: "ちばし",
    fakes: ["船橋市", "柏市", "市川市"],
    img: "img/imgSingle/chibaSingle.png",
  },
  {
    id: "13",
    name: "東京都",
    nameKana: "とうきょうと",
    city: "東京",
    cityKana: "とうきょう",
    fakes: ["杉並区", "練馬区", "足立区"],
    img: "img/imgSingle/tokyoSingle.png",
  },
  {
    id: "14",
    name: "神奈川県",
    nameKana: "かながわけん",
    city: "横浜市",
    cityKana: "よこはまし",
    fakes: ["川崎市", "神奈川市", "厚木市"],
    img: "img/imgSingle/kanagawaSingle.png",
  },
  {
    id: "15",
    name: "新潟県",
    nameKana: "にいがたけん",
    city: "新潟市",
    cityKana: "にいがたし",
    fakes: ["長岡市", "三条市", "柏崎市"],
    img: "img/imgSingle/nigataSingle.png",
  },
  {
    id: "16",
    name: "富山県",
    nameKana: "とやまけん",
    city: "富山市",
    cityKana: "とやまし",
    fakes: ["魚津市", "氷見市", "滑川市"],
    img: "img/imgSingle/toyamaSingle.png",
  },
  {
    id: "17",
    name: "石川県",
    nameKana: "いしかわけん",
    city: "金沢市",
    cityKana: "かなざわし",
    fakes: ["七尾市", "小松市", "石川市"],
    img: "img/imgSingle/ishikawaSingle.png",
  },
  {
    id: "18",
    name: "福井県",
    nameKana: "ふくいけん",
    city: "福井市",
    cityKana: "ふくいし",
    fakes: ["敦賀市", "小浜市", "大野市"],
    img: "img/imgSingle/fukuiSingle.png",
  },
  {
    id: "19",
    name: "山梨県",
    nameKana: "やまなしけん",
    city: "甲府市",
    cityKana: "こうふし",
    fakes: ["山梨市", "大月市", "都留市"],
    img: "img/imgSingle/yamanashiSingle.png",
  },
  {
    id: "20",
    name: "長野県",
    nameKana: "ながのけん",
    city: "長野市",
    cityKana: "ながのし",
    fakes: ["松本市", "上田市", "岡谷市"],
    img: "img/imgSingle/naganoSingle.png",
  },
  {
    id: "21",
    name: "岐阜県",
    nameKana: "ぎふけん",
    city: "岐阜市",
    cityKana: "ぎふし",
    fakes: ["大垣市", "各務原市", "可児市"],
    img: "img/imgSingle/gifuSingle.png",
  },
  {
    id: "22",
    name: "静岡県",
    nameKana: "しずおかけん",
    city: "静岡市",
    cityKana: "しずおかし",
    fakes: ["浜松市", "沼津市", "熱海市"],
    img: "img/imgSingle/shizuokaSingle.png",
  },
  {
    id: "23",
    name: "愛知県",
    nameKana: "あいちけん",
    city: "名古屋市",
    cityKana: "なごやし",
    fakes: ["豊田市", "岡崎市", "愛知市"],
    img: "img/imgSingle/aichiSingle.png",
  },
  {
    id: "24",
    name: "三重県",
    nameKana: "みえけん",
    city: "津市",
    cityKana: "つし",
    fakes: ["四日市市", "鈴鹿市", "三重市"],
    img: "img/imgSingle/mieSingle.png",
  },
  {
    id: "25",
    name: "滋賀県",
    nameKana: "しがけん",
    city: "大津市",
    cityKana: "おおつし",
    fakes: ["彦根市", "草津市", "滋賀市"],
    img: "img/imgSingle/shigaSingle.png",
  },
  {
    id: "26",
    name: "京都府",
    nameKana: "きょうとふ",
    city: "京都市",
    cityKana: "きょうとし",
    fakes: ["福知山市", "宇治市", "舞鶴市"],
    img: "img/imgSingle/kyotoSingle.png",
  },
  {
    id: "27",
    name: "大阪府",
    nameKana: "おおさかふ",
    city: "大阪市",
    cityKana: "おおさかし",
    fakes: ["堺市", "豊中市", "岸和田市"],
    img: "img/imgSingle/osakaSingle.png",
  },
  {
    id: "28",
    name: "兵庫県",
    nameKana: "ひょうごけん",
    city: "神戸市",
    cityKana: "こうべし",
    fakes: ["尼崎市", "西宮市", "兵庫市"],
    img: "img/imgSingle/hyogoSingle.png",
  },
  {
    id: "29",
    name: "奈良県",
    nameKana: "ならけん",
    city: "奈良市",
    cityKana: "ならし",
    fakes: ["大和高田市", "生駒市", "天理市"],
    img: "img/imgSingle/naraSingle.png",
  },
  {
    id: "30",
    name: "和歌山県",
    nameKana: "わかやまけん",
    city: "和歌山市",
    cityKana: "わかやまし",
    fakes: ["海南市", "田辺市", "御坊市"],
    img: "img/imgSingle/wakayamaSingle.png",
  },
  {
    id: "31",
    name: "鳥取県",
    nameKana: "とっとりけん",
    city: "鳥取市",
    cityKana: "とっとりし",
    fakes: ["米子市", "倉吉市", "境港市"],
    img: "img/imgSingle/tottoriSingle.png",
  },
  {
    id: "32",
    name: "島根県",
    nameKana: "しまねけん",
    city: "松江市",
    cityKana: "まつえし",
    fakes: ["浜田市", "出雲市", "島根市"],
    img: "img/imgSingle/shimaneSingle.png",
  },
  {
    id: "33",
    name: "岡山県",
    nameKana: "おかやまけん",
    city: "岡山市",
    cityKana: "おかやまし",
    fakes: ["倉敷市", "津山市", "笠岡市"],
    img: "img/imgSingle/okayamaSingle.png",
  },
  {
    id: "34",
    name: "広島県",
    nameKana: "ひろしまけん",
    city: "広島市",
    cityKana: "ひろしまし",
    fakes: ["福山市", "呉市", "三原市"],
    img: "img/imgSingle/hiroshimaSingle.png",
  },
  {
    id: "35",
    name: "山口県",
    nameKana: "やまぐちけん",
    city: "山口市",
    cityKana: "やまぐちし",
    fakes: ["下関市", "宇部市", "萩市"],
    img: "img/imgSingle/yamaguchiSingle.png",
  },
  {
    id: "36",
    name: "徳島県",
    nameKana: "とくしまけん",
    city: "徳島市",
    cityKana: "とくしまし",
    fakes: ["鳴門市", "小松島市", "阿南市"],
    img: "img/imgSingle/tokushimaSingle.png",
  },
  {
    id: "37",
    name: "香川県",
    nameKana: "かがわけん",
    city: "高松市",
    cityKana: "たかまつし",
    fakes: ["丸亀市", "坂出市", "香川市"],
    img: "img/imgSingle/kagawaSingle.png",
  },
  {
    id: "38",
    name: "愛媛県",
    nameKana: "えひめけん",
    city: "松山市",
    cityKana: "まつやまし",
    fakes: ["愛媛市", "西条市", "宇和島市"],
    img: "img/imgSingle/ehimeSingle.png",
  },
  {
    id: "39",
    name: "高知県",
    nameKana: "こうちけん",
    city: "高知市",
    cityKana: "こうちし",
    fakes: ["宿毛市", "安芸市", "南国市"],
    img: "img/imgSingle/kochiSingle.png",
  },
  {
    id: "40",
    name: "福岡県",
    nameKana: "ふくおかけん",
    city: "福岡市",
    cityKana: "ふくおかし",
    fakes: ["北九州市", "久留米市", "直方市"],
    img: "img/imgSingle/fukuokaSingle.png",
  },
  {
    id: "41",
    name: "佐賀県",
    nameKana: "さがけん",
    city: "佐賀市",
    cityKana: "さがし",
    fakes: ["唐津市", "鳥栖市", "多久市"],
    img: "img/imgSingle/sagaSingle.png",
  },
  {
    id: "42",
    name: "長崎県",
    nameKana: "ながさきけん",
    city: "長崎市",
    cityKana: "ながさきし",
    fakes: ["佐世保市", "島原市", "諫早市"],
    img: "img/imgSingle/nagasakiSingle.png",
  },
  {
    id: "43",
    name: "熊本県",
    nameKana: "くまもとけん",
    city: "熊本市",
    cityKana: "くまもとし",
    fakes: ["八代市", "人吉市", "天草市"],
    img: "img/imgSingle/kumamotoSingle.png",
  },
  {
    id: "44",
    name: "大分県",
    nameKana: "おおいたけん",
    city: "大分市",
    cityKana: "おおいたし",
    fakes: ["別府市", "中津市", "日田市"],
    img: "img/imgSingle/oitaSingle.png",
  },
  {
    id: "45",
    name: "宮崎県",
    nameKana: "みやざきけん",
    city: "宮崎市",
    cityKana: "みやざきし",
    fakes: ["都城市", "延岡市", "日南市"],
    img: "img/imgSingle/miyazakiSingle.png",
  },
  {
    id: "46",
    name: "鹿児島県",
    nameKana: "かごしまけん",
    city: "鹿児島市",
    cityKana: "かごしまし",
    fakes: ["鹿屋市", "指宿市", "枕崎市"],
    img: "img/imgSingle/kagoshimaSingle.png",
  },
  {
    id: "47",
    name: "沖縄県",
    nameKana: "おきなわけん",
    city: "那覇市",
    cityKana: "なはし",
    fakes: ["沖縄市", "石垣市", "浦添市"],
    img: "img/imgSingle/okinawaSingle.png",
  },
];
